// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type HelloReq struct {
	Name string `form:"name,optional"`
}

type HelloResp struct {
	Name string `json:"name"`
}

type ResolveReq struct {
	Code string `form:"code"`
}

type ResolveResp struct {
	LongUrl string `json:"longUrl"`
}

type ShortenReq struct {
	LongUrl string `json:"longUrl"`
}

type ShortenResp struct {
	Code string `json:"code"`
}

type Resp struct {
	Msg string `json:"msg"`
}
