// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: greet.proto

package server

import (
	"context"

	"shorturl/quickstart-micro/greet/rpc/internal/logic"
	"shorturl/quickstart-micro/greet/rpc/internal/svc"
	"shorturl/quickstart-micro/greet/rpc/pb"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

func (s *GreetServer) Ping(ctx context.Context, in *pb.Placeholder) (*pb.Placeholder, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *GreetServer) Hello(ctx context.Context, in *pb.HelloReq) (*pb.HelloResp, error) {
	l := logic.NewHelloLogic(ctx, s.svcCtx)
	return l.Hello(in)
}

func (s *GreetServer) Shorten(ctx context.Context, in *pb.ShortenReq) (*pb.ShortenResp, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}

func (s *GreetServer) Resolve(ctx context.Context, in *pb.ResolveReq) (*pb.ResolveResp, error) {
	l := logic.NewResolveLogic(ctx, s.svcCtx)
	return l.Resolve(in)
}
