// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: greet.proto

package greet

import (
	"context"

	"shorturl/quickstart-micro/greet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HelloReq    = pb.HelloReq
	HelloResp   = pb.HelloResp
	Placeholder = pb.Placeholder
	ResolveReq  = pb.ResolveReq
	ResolveResp = pb.ResolveResp
	ShortenReq  = pb.ShortenReq
	ShortenResp = pb.ShortenResp

	Greet interface {
		Ping(ctx context.Context, in *Placeholder, opts ...grpc.CallOption) (*Placeholder, error)
		Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
		Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error)
		Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*ResolveResp, error)
	}

	defaultGreet struct {
		cli zrpc.Client
	}
)

func NewGreet(cli zrpc.Client) Greet {
	return &defaultGreet{
		cli: cli,
	}
}

func (m *defaultGreet) Ping(ctx context.Context, in *Placeholder, opts ...grpc.CallOption) (*Placeholder, error) {
	client := pb.NewGreetClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultGreet) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	client := pb.NewGreetClient(m.cli.Conn())
	return client.Hello(ctx, in, opts...)
}

func (m *defaultGreet) Shorten(ctx context.Context, in *ShortenReq, opts ...grpc.CallOption) (*ShortenResp, error) {
	client := pb.NewGreetClient(m.cli.Conn())
	return client.Shorten(ctx, in, opts...)
}

func (m *defaultGreet) Resolve(ctx context.Context, in *ResolveReq, opts ...grpc.CallOption) (*ResolveResp, error) {
	client := pb.NewGreetClient(m.cli.Conn())
	return client.Resolve(ctx, in, opts...)
}
