// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"shorturl/quickstart-micro/greet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/hello",
				Handler: HelloHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resolve",
				Handler: ResolveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/shorten",
				Handler: ShortenHandler(serverCtx),
			},
		},
	)
}
